# [package]
# name = "tiramisu_os"
# version = "0.1.0"
# edition = "2021"
# authors = ["cA0"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
resolver = "2"
members = [
    "kernel/[!.]*/"
]

default-members = [
    "kernel/tiramisu_bootloader"
]

# [dependencies]

# workaround rust-lang/rust#47074
[profile.dev]
codegen-units = 1
incremental = false

# workaround rust-lang/rust#47074
[profile.release]
codegen-units = 1
incremental = false