[package]
name = "vga_text_mode"
version = "0.1.0"
edition = "2021"
authors = ["cA0"]
description = "VGA text mode buffer."

[dependencies]
lazy_static = { version = "1.5.0", features = ["spin_no_std"] }
spin = "0.9.8"

[lib]
crate-type = ["rlib"]