[package]
name = "vga_text_mode"
version = "0.1.0"
edition = "2021"
authors = ["cA0"]
description = "VGA text mode buffer."

[dependencies]
lazy_static = { workspace = true }
spin = { workspace = true }

[lib]
crate-type = ["rlib"]