[package]
name = "tiramisu_bootloader"
version = "0.1.0"
edition = "2021"
authors = ["cA0"]
description = "Minimalist crate for booting up Tiramisu OS. ASM segment, passed to ignition.rs, then passed on to ___"

[lib]
crate-type = ["staticlib"]